name: Continuous Integration

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]
      

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.DO_DEPLOY_IP }}
          username: ${{ secrets.DO_DEPLOY_USERNAME }}
          key: ${{ secrets.DO_DEPLOY_KEY }}
          script: |
              pm2 del all &&
              cd ~/idem-exchange/ &&
              git stash && 
              git checkout development &&
              git pull &&
              cd ~/idem-exchange/client &&
              yarn && 
              pm2 start "yarn start" --name "client"
              cd ~/idem-exchange/server &&
              yarn &&
              pm2 start "yarn start" --name "server"
              
